//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public int MANAGER_ID { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public int DEP_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
